language: go
go:
  - "1.8.x"
dist: trusty
sudo: required
group: edge

services:
  - docker
before_script:
  - travis_wait 30 ./setup-gate.sh
  - sudo docker ps -a
  - sudo docker logs origin
  - make vendor
  - make install
#  - bash <(curl -s https://raw.githubusercontent.com/openshift/ansible-service-broker/master/setup-gate.sh)
#  - go get github.com/rthallisey/service-broker-ci/tree/master/cmd/ci
script:
  - ci
