language: go
go:
  - "1.8.x"
dist: trusty
sudo: required
group: edge

before_script:
  - go get github.com/rthallisey/service-broker-ci/tree/master/cmd/ci
script:
  - bash <(curl -s https://raw.githubusercontent.com/openshift/ansible-service-broker/master/scripts/run_latest_build.sh)
  - ci
