language: go
go:
  - "1.8.x"
dist: trusty
sudo: required
group: edge

before_script:
  - sudo wget -O /bin/oc https://s3.amazonaws.com/catasb/linux/amd64/oc
  - sudo chmod +x /bin/oc
#  - go get github.com/rthallisey/service-broker-ci/tree/master/cmd/ci
script:
  - bash <(curl -s https://raw.githubusercontent.com/openshift/ansible-service-broker/master/scripts/run_latest_build.sh)
  - ci
