language: go
go:
  - "1.8.x"
dist: trusty
sudo: required
group: edge

services:
  - docker
before_script:
  - wget -O /tmp/glide.tar.gz https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz
  - tar xfv /tmp/glide.tar.gz -C /tmp
  - sudo mv $(find /tmp -name "glide") /usr/bin
  - sudo wget -O /bin/oc https://s3.amazonaws.com/catasb/linux/amd64/oc
  - sudo chmod +x /bin/oc
  - echo '{"insecure-registries":["172.30.0.0/16"]}' | sudo tee /etc/docker/daemon.json
  - sudo mount --make-shared /
  - sudo service docker restart
  - make vendor
  - make install
script:
  - ci
