provision: rthallisey/service-broker-ci/mediawiki123
verify: wait-for-resource.sh create pod mediawiki openshift

provision: rthallisey/service-broker-ci/postgresql
verify: wait-for-resource.sh create pod postgresql openshift

bind: rthallisey/service-broker-ci/postgresql
verify: wait-for-resource.sh create bindings.v1alpha1.servicecatalog.k8s.io binding

# The verify field is run as a shell command
verify: verify-bind.sh mediawiki123

# The BindTarget gets binded to the BindApp.
# Format:
#      <BindTarget> | <BindApp>
#
unbind: postgresql | mediawiki123
verify: wait-for-resource.sh delete bindings.v1alpha1.servicecatalog.k8s.io binding

deprovision: rthallisey/service-broker-ci/mediawiki123
verify: wait-for-resource.sh delete pod mediawiki openshift

deprovision: rthallisey/service-broker-ci/postgresql
verify: wait-for-resource.sh delete pod postgresql openshift
