provision: ansibleplaybookbundle/mediawiki123
provision: ansibleplaybookbundle/postgresql
# Verify provision was successful

bind: ansibleplaybookbundle/postgresql
# Verify bind was successful

verify: verify-app.sh
# Run as a shell command

unbind: ansibleplaybookbundle/postgresql
# Automatic verification occurs after the unbind

deprovision: ansibleplaybookbundle/mediawiki123
deprovision: ansibleplaybookbundle/postgresql
# Automatic verification occurs after the deprovision
