provision: ansibleplaybookbundle/mediawiki123-apb
provision: ansibleplaybookbundle/postgresql-apb
# Verify provision was successful

bind: ansibleplaybookbundle/postgresql-apb
# Verify bind was successful

verify: verify-app.sh
# Run as a shell command

unbind: ansibleplaybookbundle/postgresql-apb
# Automatic verification occurs after the unbind

deprovision: ansibleplaybookbundle/mediawiki123-apb
deprovision: ansibleplaybookbundle/postgresql-apb
# Automatic verification occurs after the deprovision
