provision: rthallisey/service-broker-ci/mediawiki123

provision: rthallisey/service-broker-ci/postgresql

bind: rthallisey/service-broker-ci/postgresql

# The verify field is run as a shell command
verify: verify-bind.sh mediawiki123

# The BindApp is the application that will be binded to the BindTarget.
# Format:
#      <BindApp> | <BindTarget>
#
unbind: postgresql | mediawiki123

deprovision: rthallisey/service-broker-ci/mediawiki123

deprovision: rthallisey/service-broker-ci/postgresql
