provision: rthallisey/service-broker-ci/mediawiki123
verify: openshift/ansible-service-broker/scripts/broker-ci/wait-for-resource.sh create mediawiki

provision: rthallisey/service-broker-ci/postgresql

# Verify provision was successful

bind: rthallisey/service-broker-ci/postgresql
# Verify bind was successful

verify: verify-app.sh
# Run as a shell command

unbind: rthallisey/service-broker-ci/postgresql
# Automatic verification occurs after the unbind

deprovision: rthallisey/service-broker-ci/mediawiki123
deprovision: rthallisey/service-broker-ci/postgresql
# Automatic verification occurs after the deprovision
